import Head from 'next/head'
import CommentModal from '../components/CommentModal';
import Feed from "../components/Feed";
import Sidebar from '../components/Sidebar';
import Widgets from '../components/Widgets';

export default function Home({newsResults}) {
  return (
    <div>
      <Head>
        <title>RUBars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="fireicon.png" />
      </Head>

      <main className="flex min-h-screen mx-auto">
        {/* Sidebar */}
      <Sidebar/>

      {/* Feed */}

      <Feed/>


      {/* Widgets */}
      <Widgets newsResults={newsResults.articles}/>
      {/* Modal */}

      <CommentModal/>
      </main>

    </div>
  );
}


// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json


export async function getServerSideProps(){
  const newsResults = await fetch ("https://saurav.tech/NewsAPI/top-headlines/category/business/us.json").then((res)=>res.json());

  // Who to follow section

  // const randomUsersResults = await fetch()
  return{
    props:{
      newsResults,
    }
  }
}
